const PDFDocument = require("pdfkit");

const generateReportPDF = (reportData, res) => {

    const {
        candidate,
        interview,
        report,
        questions
    } = reportData;

    const doc = new PDFDocument({
        margin: 50
    });

    // Browser ko PDF response
    res.setHeader(
        "Content-Type",
        "application/pdf"
    );

    res.setHeader(
        "Content-Disposition",
        `attachment; filename="Interview_Report.pdf"`
    );

    doc.pipe(res);

    // =========================
    // TITLE
    // =========================

    doc
        .fontSize(24)
        .text(
            "AI Interview Report",
            {
                align: "center"
            }
        );

    doc.moveDown(1);

    // =========================
    // CANDIDATE DETAILS
    // =========================

    doc
        .fontSize(16)
        .text("Candidate Details");

    doc.moveDown(0.5);

    doc
        .fontSize(11)
        .text(`Name: ${candidate.name}`)
        .text(`Email: ${candidate.email}`)
        .text(`Role: ${interview.role}`)
        .text(`Difficulty: ${interview.difficulty}`)
        .text(`Total Questions: ${interview.totalQuestions}`)
        .text(`Status: ${interview.status}`);

    doc.moveDown(1);

    // =========================
    // SCORE SUMMARY
    // =========================

    doc
        .fontSize(16)
        .text("Performance Summary");

    doc.moveDown(0.5);

    doc
        .fontSize(11)
        .text(`Technical: ${report.technical}/10`)
        .text(`Communication: ${report.communication}/10`)
        .text(`Confidence: ${report.confidence}/10`)
        .text(`Project Knowledge: ${report.projectKnowledge}/10`)
        .text(`Problem Solving: ${report.problemSolving}/10`)
        .text(`Overall Score: ${report.overallScore}/10`);

    doc.moveDown(1);

    // =========================
    // STRENGTHS
    // =========================

    doc
        .fontSize(16)
        .text("Strengths");

    doc.moveDown(0.5);

    if (report.strengths?.length) {

        report.strengths.forEach((strength) => {

            doc
                .fontSize(11)
                .text(`• ${strength}`);

        });

    } else {

        doc
            .fontSize(11)
            .text("No strengths recorded.");

    }

    doc.moveDown(1);

    // =========================
    // WEAKNESSES
    // =========================

    doc
        .fontSize(16)
        .text("Areas for Improvement");

    doc.moveDown(0.5);

    if (report.weaknesses?.length) {

        report.weaknesses.forEach((weakness) => {

            doc
                .fontSize(11)
                .text(`• ${weakness}`);

        });

    } else {

        doc
            .fontSize(11)
            .text("No weaknesses recorded.");

    }

    doc.moveDown(1);

    // =========================
    // RECOMMENDATIONS
    // =========================

    doc
        .fontSize(16)
        .text("Recommendations");

    doc.moveDown(0.5);

    if (report.recommendations?.length) {

        report.recommendations.forEach((recommendation) => {

            doc
                .fontSize(11)
                .text(`• ${recommendation}`);

        });

    } else {

        doc
            .fontSize(11)
            .text("No recommendations available.");

    }

    // =========================
    // QUESTION DETAILS
    // =========================

    doc.addPage();

    doc
        .fontSize(18)
        .text("Interview Questions & Answers");

    doc.moveDown(1);

    questions.forEach((item, index) => {

        doc
            .fontSize(13)
            .text(
                `Question ${index + 1}:`
            );

        doc
            .fontSize(11)
            .text(
                item.question || "N/A"
            );

        doc.moveDown(0.3);

        doc
            .fontSize(11)
            .text(
                `Answer: ${item.answer || "Not answered"}`
            );

        doc.moveDown(0.3);

        doc
            .text(
                `Score: ${item.score}/10`
            );

        doc.moveDown(0.3);

        doc
            .text(
                `Feedback: ${item.feedback || "No feedback"}`
            );

        doc.moveDown(1);

    });

    // =========================
    // FOOTER
    // =========================

    doc
        .fontSize(9)
        .text(
            "Generated by SkillForge AI",
            50,
            750,
            {
                align: "center"
            }
        );

    doc.end();
};

module.exports = generateReportPDF;